### PR TITLE
Fix updateAll for model instance as input

### LINKED ISSUE #71: udpateAll( ) fails if input data object is a LoopBack model instance
### Description of feature (or steps to reproduce if bug)
When `updateAll()` is invoked with loopback `model` instance as payload, it fails with complaining: `Bad special document member: __cachedRelations` and similar. 
Other NoSQL connector i.e. mongo connector, AFAIK, supports `model` instance as payload.

### PR DESCRIPTION
**Pull request by gunjpan**
invoking updateAll() with input data in loopback
model instance format was causing failures as
it was not converted to canonical presentation.

This fix resolves it by checking if input data
is a model instance and if it is, convert it to
a plain JSON object for update.

Fixes #71

#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by gunjpan** [comment]
Linter failing :man_facepalming:

File: lib/cloudant.js [hunk 1]
```diff
@@ -522,6 +524,19 @@ Cloudant.prototype.updateAttributes = function(model, id, data, options, cb) {
...
+ * REST endpoint as remoting converts it to model if endpoint expects a
+ * model instance
+ */
+
+function getPlainJSONData(model, data) {
+  if (this._models[model] && data instanceof this._models[model].model) {
+    return data.toJSON();
+  }
+  return data;
+}
```
Comment (kjdelisle) [inline lib/cloudant.js]: It might be that I don't understand exactly what's happening here, but it seems to me like this function is the sort of thing that would happen in the base connector repository, and not in this particular one. How is this handled in other connectors?

Comment (gunjpan) [inline lib/cloudant.js]: AFAIK, this function i.e. parsing data from model instance is not present in the base connector and in other connectors, there is some sort of cleanup built-in for input data.
Thus, defined parsing of input data here in the connector.

Comment (gunjpan) [inline lib/cloudant.js]: @kjdelisle : :point_up: FYI

**Comment by gunjpan** [comment]
@kjdelisle : Is this good to land?

**Comment by kjdelisle** [comment]
LGTM
